Add new resource and data source for Virtual Hub
neil-yechenwei/terraform-provider-azurerm pull request #5
Opened 2019-08-22 04:18 UTC by neil-yechenwei

2019-08-29 01:34 UTC, WodansSon requested changes
@neil-yechenwei The is looking very good, there are only two things I would to see updated. Can we get a couple of more test cases (comment below) and the TOC seems to be out of sync... can you pull from master and get that in sync again?

2019-08-29 01:34 UTC, WodansSon commented on azurerm/resource_arm_virtual_hub_test.go
> +
Can we get an Update and a Complete test in here too?

2019-08-29 09:51 UTC, neil-yechenwei commented on azurerm/resource_arm_virtual_hub_test.go
> +
Sure. I've added update test and complete test. Thanks.

2019-08-29 09:52 UTC, neil-yechenwei commented
> @neil-yechenwei The is looking very good, there are only two things I would to see updated. Can we get a couple of more test cases (comment below) and the TOC seems to be out of sync... can you pull from master and get that in sync again?

I've also updated TOC. Thanks.

2019-09-18 02:03 UTC, WodansSon requested changes
Hey @neil-yechenwei , thanks for the PR... this mostly LGTM, I have left a few mostly minor comments in the PR. 🚀

2019-09-18 02:03 UTC, WodansSon commented on azurerm/resource_arm_virtual_hub.go
> +				Optional: true,
Can we add some validation here? WDYT?

```suggestion
				Optional: true,
				ValidateFunc: validate.NoEmptyStrings,
```

2019-09-18 02:03 UTC, WodansSon commented on azurerm/resource_arm_virtual_hub.go
> +			"express_route_gateway": {
can we flatten this attribute to `express_route_gateway_id`?

2019-09-18 02:03 UTC, WodansSon commented on azurerm/resource_arm_virtual_hub.go
> +			"p2svpn_gateway": {
same here, can we flatten this to `p2svpn_gateway_id`?

2019-09-18 02:03 UTC, WodansSon commented on azurerm/resource_arm_virtual_hub.go
> +			"tags": tags.Schema(),
Can we move this to the bottom of the schema definition?

2019-09-18 02:03 UTC, WodansSon commented on azurerm/resource_arm_virtual_hub.go
> +						"remote_virtual_network": {
can we flatten this attribute to `remote_virtual_network_id`

2019-09-18 02:03 UTC, WodansSon commented on azurerm/resource_arm_virtual_hub.go
> +				Type:     schema.TypeList,
same here, can we flatten this the `virtual_wan_id`?

2019-09-18 02:03 UTC, WodansSon commented on azurerm/resource_arm_virtual_hub.go
> +			"vpn_gateway": {
and here, can we flatten this to `vpn_gateway_id`?

2019-09-18 02:03 UTC, WodansSon commented on azurerm/data_source_virtual_hub.go
> +			"express_route_gateway": {
can we flatten this to `express_route_gateway_id`?

2019-09-18 02:03 UTC, WodansSon commented on azurerm/data_source_virtual_hub.go
> +			"p2svpn_gateway": {
can we flatten this to `p2svpn_gateway_id`?

2019-09-18 02:03 UTC, WodansSon commented on azurerm/data_source_virtual_hub.go
> +						"remote_virtual_network": {
can we flatten this to `remote_virtual_network_id`?

2019-09-18 02:03 UTC, WodansSon commented on azurerm/data_source_virtual_hub.go
> +			"virtual_wan": {
same here, can we flatten this to `virtual_wan_id`?

2019-09-18 02:03 UTC, WodansSon commented on azurerm/data_source_virtual_hub.go
> +			"vpn_gateway": {
again here, can we flatten this to `vpn_gateway_id`?

2019-09-18 02:03 UTC, WodansSon commented on azurerm/resource_arm_virtual_hub_test.go
> +			},
can we add a new step where it updates back to the basic state and then have an import check?

2019-09-18 03:15 UTC, neil-yechenwei commented on azurerm/resource_arm_virtual_hub.go
> +				Optional: true,
updated

2019-09-18 03:16 UTC, neil-yechenwei commented on azurerm/resource_arm_virtual_hub.go
> +			"tags": tags.Schema(),
Updated

2019-09-18 06:17 UTC, neil-yechenwei commented on azurerm/resource_arm_virtual_hub.go
> +			"express_route_gateway": {
Updated

2019-09-18 06:17 UTC, neil-yechenwei commented on azurerm/resource_arm_virtual_hub.go
> +			"p2svpn_gateway": {
Updated

2019-09-18 06:17 UTC, neil-yechenwei commented on azurerm/resource_arm_virtual_hub.go
> +						"remote_virtual_network": {
Updated

2019-09-18 06:17 UTC, neil-yechenwei commented on azurerm/resource_arm_virtual_hub.go
> +				Type:     schema.TypeList,
Updated

2019-09-18 06:17 UTC, neil-yechenwei commented on azurerm/resource_arm_virtual_hub.go
> +			"vpn_gateway": {
Updated

2019-09-18 06:17 UTC, neil-yechenwei commented on azurerm/data_source_virtual_hub.go
> +			"express_route_gateway": {
Updated

2019-09-18 06:17 UTC, neil-yechenwei commented on azurerm/data_source_virtual_hub.go
> +			"p2svpn_gateway": {
Updated

2019-09-18 06:18 UTC, neil-yechenwei commented on azurerm/data_source_virtual_hub.go
> +						"remote_virtual_network": {
Updated

2019-09-18 06:18 UTC, neil-yechenwei commented on azurerm/data_source_virtual_hub.go
> +			"virtual_wan": {
Updated

2019-09-18 06:18 UTC, neil-yechenwei commented on azurerm/data_source_virtual_hub.go
> +			"vpn_gateway": {
Updated

2019-09-18 07:42 UTC, neil-yechenwei commented on azurerm/resource_arm_virtual_hub_test.go
> +			},
Updated

2019-09-20 08:23 UTC, neil-yechenwei commented
@jeffreyCline , Thanks for your comments. I've updated code. Please help to take a look. Thanks.

2022-10-27 06:48 UTC, closed without merging